package test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import rpg.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.04 12:56:34 // Generated by ComTest
 *
 */
public class EsineTest {
    ///



  // Generated by ComTest BEGIN
  /** testToString119 */
  @Test
  public void testToString119() {    // Esine: 119
    Esine esine = new Esine(); 
    esine.parse("2|Ankka Aku"); 
    assertEquals("From: Esine line: 122", true, esine.toString().startsWith("2|Ankka Aku|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse139 */
  @Test
  public void testParse139() {    // Esine: 139
    Esine esine = new Esine(); 
    esine.parse("   1   | Kirves "); 
    assertEquals("From: Esine line: 142", 1, esine.getIDnumero()); 
    assertEquals("From: Esine line: 143", true, esine.toString().startsWith("1|Kirves|")); 
    esine.rekisteroi(); 
    int n = esine.getIDnumero(); 
    esine.parse(""+(n+20)); 
    esine.rekisteroi(); 
    assertEquals("From: Esine line: 149", n+20+1, esine.getIDnumero()); 
  } // Generated by ComTest END
}