package test;
// Generated by ComTest BEGIN
import java.io.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import rpg.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.04 14:50:02 // Generated by ComTest
 *
 */
public class RodutTest {



  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta48 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta48() throws SailoException {    // Rodut: 48
    Rodut harrasteet = new Rodut(); 
    Rotu miekka = new Rotu(); miekka.taytaRotu(0); 
    Rotu kirves = new Rotu(); kirves.taytaRotu(1); 
    String tiedNimi = "testikelmit"; 
    File ftied = new File(tiedNimi+".dat"); 
    ftied.delete(); 
    try {
    harrasteet.lueTiedostosta(tiedNimi); 
    fail("Rodut: 58 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    harrasteet.lisaa(kirves); 
    harrasteet.lisaa(miekka); 
    harrasteet.tallenna(); 
    harrasteet = new Rodut(); 
    harrasteet.lueTiedostosta(tiedNimi); 
    Iterator<Rotu> i = harrasteet.iterator(); 
    assertEquals("From: Rodut line: 65", miekka.toString(), i.next().toString()); 
    assertEquals("From: Rodut line: 66", true, i.hasNext()); 
    harrasteet.lisaa(miekka); 
    harrasteet.lisaa(kirves); 
    harrasteet.tallenna(); 
    assertEquals("From: Rodut line: 70", true, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: Rodut line: 72", true, fbak.delete()); 
  } // Generated by ComTest END
}