package test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import rpg.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.04 14:35:54 // Generated by ComTest
 *
 */
public class RotuTest {
    ///



  // Generated by ComTest BEGIN
  /** testToString101 */
  @Test
  public void testToString101() {    // Rotu: 101
    Rotu rotu = new Rotu(); 
    rotu.parse("2"); 
    assertEquals("From: Rotu line: 104", true, rotu.toString().startsWith("2")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse120 */
  @Test
  public void testParse120() {    // Rotu: 120
    Rotu esine = new Rotu(); 
    esine.parse("   1   "); 
    assertEquals("From: Rotu line: 123", 1, esine.getRotuID()); 
    assertEquals("From: Rotu line: 124", true, esine.toString().startsWith("1|")); 
    esine.rekisteroi(); 
    int n = esine.getRotuID(); 
    esine.parse(""+(n+20)); 
    esine.rekisteroi(); 
    assertEquals("From: Rotu line: 130", n+20+1, esine.getRotuID()); 
  } // Generated by ComTest END
}