package rpg;
// Generated by ComTest BEGIN
import java.io.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import rpg.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.04 15:22:15 // Generated by ComTest
 *
 */
public class HahmojenEsineetTest {
    ///



  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta85 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta85() throws SailoException {    // HahmojenEsineet: 85
    HahmojenEsineet harrasteet = new HahmojenEsineet(); 
    HahmonEsine miekka = new HahmonEsine(1,1); 
    HahmonEsine kirves = new HahmonEsine(2,2); 
    String tiedNimi = "testikelmit"; 
    File ftied = new File(tiedNimi+".dat"); 
    ftied.delete(); 
    try {
    harrasteet.lueTiedostosta(tiedNimi); 
    fail("HahmojenEsineet: 95 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    harrasteet.lisaa(kirves); 
    harrasteet.lisaa(miekka); 
    harrasteet.tallenna(); 
    harrasteet = new HahmojenEsineet(); 
    harrasteet.lueTiedostosta(tiedNimi); 
    Iterator<HahmonEsine> i = harrasteet.iterator(); 
    assertEquals("From: HahmojenEsineet line: 102", miekka.toString(), i.next().toString()); 
    assertEquals("From: HahmojenEsineet line: 103", false, i.hasNext()); 
    harrasteet.lisaa(miekka); 
    harrasteet.lisaa(kirves); 
    harrasteet.tallenna(); 
    assertEquals("From: HahmojenEsineet line: 107", true, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: HahmojenEsineet line: 109", true, fbak.delete()); 
  } // Generated by ComTest END
}