package rpg;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import rpg.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.04 12:49:16 // Generated by ComTest
 *
 */
public class HahmoTest {



  // Generated by ComTest BEGIN
  /** testGetNimi41 */
  @Test
  public void testGetNimi41() {    // Hahmo: 41
    Hahmo aku = new Hahmo(); 
    aku.taytaAkuAnkka(); 
    aku.getNimi().equals("Ankka Aku"); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString151 */
  @Test
  public void testToString151() {    // Hahmo: 151
    Hahmo hahmo = new Hahmo(); 
    hahmo.parse("2|Ankka Aku|18"); 
    assertEquals("From: Hahmo line: 154", true, hahmo.toString().startsWith("2|Ankka Aku|18|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse185 */
  @Test
  public void testParse185() {    // Hahmo: 185
    Hahmo hahmo = new Hahmo(); 
    hahmo.parse("   3   | Ankka Aku | 18"); 
    assertEquals("From: Hahmo line: 188", 3, hahmo.getTunnusNro()); 
    assertEquals("From: Hahmo line: 189", true, hahmo.toString().startsWith("3|Ankka Aku|18|")); 
    hahmo.rekisteroi(); 
    int n = hahmo.getTunnusNro(); 
    hahmo.parse(""+(n+20)); 
    hahmo.rekisteroi(); 
    assertEquals("From: Hahmo line: 195", n+20+1, hahmo.getTunnusNro()); 
  } // Generated by ComTest END
}