package rpg.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import rpg.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.03 22:34:15 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class EsineTest {



  // Generated by ComTest BEGIN
  /** testToString140 */
  @Test
  public void testToString140() {    // Esine: 140
    Esine esine = new Esine(); 
    esine.parse("2|Ankka Aku"); 
    assertEquals("From: Esine line: 143", true, esine.toString().startsWith("2|Ankka Aku|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse160 */
  @Test
  public void testParse160() {    // Esine: 160
    Esine esine = new Esine(); 
    esine.parse("   1   | Kirves "); 
    assertEquals("From: Esine line: 163", 1, esine.getIDnumero()); 
    assertEquals("From: Esine line: 164", true, esine.toString().startsWith("1|Kirves|")); 
    esine.rekisteroi(); 
    int n = esine.getIDnumero(); 
    esine.parse(""+(n+20)); 
    esine.rekisteroi(); 
    assertEquals("From: Esine line: 170", n+20+1, esine.getIDnumero()); 
  } // Generated by ComTest END
}