package rpg.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import rpg.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.03 22:47:30 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class HahmoTest {



  // Generated by ComTest BEGIN
  /** testGetNimi57 */
  @Test
  public void testGetNimi57() {    // Hahmo: 57
    Hahmo aku = new Hahmo(); 
    aku.taytaAkuAnkka(); 
    aku.getNimi().equals("Ankka Aku"); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString368 */
  @Test
  public void testToString368() {    // Hahmo: 368
    Hahmo hahmo = new Hahmo(); 
    hahmo.parse("2|Ankka Aku|18"); 
    assertEquals("From: Hahmo line: 371", true, hahmo.toString().startsWith("2|Ankka Aku|18|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse403 */
  @Test
  public void testParse403() {    // Hahmo: 403
    Hahmo hahmo = new Hahmo(); 
    hahmo.parse("   3   | Ankka Aku | 18"); 
    assertEquals("From: Hahmo line: 406", 3, hahmo.getTunnusNro()); 
    assertEquals("From: Hahmo line: 407", true, hahmo.toString().startsWith("3|Ankka Aku|18|")); 
    hahmo.rekisteroi(); 
    int n = hahmo.getTunnusNro(); 
    hahmo.parse(""+(n+20)); 
    hahmo.rekisteroi(); 
    assertEquals("From: Hahmo line: 413", n+20+1, hahmo.getTunnusNro()); 
  } // Generated by ComTest END
}