package rpg.test;
// Generated by ComTest BEGIN
import java.io.File;
import rpg.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.03 22:51:58 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class HahmotTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa93 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa93() throws SailoException {    // Hahmot: 93
    Hahmot hahmot = new Hahmot(); 
    Hahmo aku1 = new Hahmo(); Hahmo aku2 = new Hahmo(); 
    assertEquals("From: Hahmot line: 97", 0, hahmot.getLkm()); 
    hahmot.lisaa(aku1); assertEquals("From: Hahmot line: 98", 1, hahmot.getLkm()); 
    hahmot.lisaa(aku2); assertEquals("From: Hahmot line: 99", 2, hahmot.getLkm()); 
    hahmot.lisaa(aku1); assertEquals("From: Hahmot line: 100", 3, hahmot.getLkm()); 
    Iterator<Hahmo> it = hahmot.iterator(); 
    assertEquals("From: Hahmot line: 102", aku1, it.next()); 
    assertEquals("From: Hahmot line: 103", aku2, it.next()); 
    assertEquals("From: Hahmot line: 104", aku1, it.next()); 
    hahmot.lisaa(aku1); assertEquals("From: Hahmot line: 105", 4, hahmot.getLkm()); 
    hahmot.lisaa(aku1); assertEquals("From: Hahmot line: 106", 5, hahmot.getLkm()); 
    hahmot.lisaa(aku1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta141 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta141() throws SailoException {    // Hahmot: 141
    Hahmot jasenet = new Hahmot(); 
    Hahmo aku1 = new Hahmo(), aku2 = new Hahmo(); 
    aku1.taytaAkuAnkka(); 
    aku2.taytaAkuAnkka(); 
    String hakemisto = "testikelmit"; 
    String tiedNimi = hakemisto+"/nimet"; 
    File ftied = new File(tiedNimi+".dat"); 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    ftied.delete(); 
    try {
    jasenet.lueTiedostosta(tiedNimi); 
    fail("Hahmot: 155 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    jasenet.lisaa(aku1); 
    jasenet.lisaa(aku2); 
    jasenet.tallenna(); 
    jasenet = new Hahmot();  // Poistetaan vanhat luomalla uusi
    jasenet.lueTiedostosta(tiedNimi);  // johon ladataan tiedot tiedostosta.
    Iterator<Hahmo> i = jasenet.iterator(); 
    assertEquals("From: Hahmot line: 162", aku1, i.next()); 
    assertEquals("From: Hahmot line: 163", aku2, i.next()); 
    assertEquals("From: Hahmot line: 164", false, i.hasNext()); 
    jasenet.lisaa(aku2); 
    jasenet.tallenna(); 
    assertEquals("From: Hahmot line: 167", true, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: Hahmot line: 169", true, fbak.delete()); 
    assertEquals("From: Hahmot line: 170", true, dir.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testHahmotIterator284 
   * @throws SailoException when error
   */
  @Test
  public void testHahmotIterator284() throws SailoException {    // Hahmot: 284
    Hahmot hahmot = new Hahmot(); 
    Hahmo aku1 = new Hahmo(), aku2 = new Hahmo(); 
    aku1.rekisteroi(); aku2.rekisteroi(); 
    hahmot.lisaa(aku1); 
    hahmot.lisaa(aku2); 
    hahmot.lisaa(aku1); 
    StringBuffer ids = new StringBuffer(30); 
    for (Hahmo hahmo:hahmot) // Kokeillaan for-silmukan toimintaa
    ids.append(" "+hahmo.getTunnusNro()); 
    String tulos = " " + aku1.getTunnusNro() + " " + aku2.getTunnusNro() + " " + aku1.getTunnusNro(); 
    assertEquals("From: Hahmot line: 303", tulos, ids.toString()); 
    ids = new StringBuffer(30); 
    for (Iterator<Hahmo>  i=hahmot.iterator(); i.hasNext(); ) { // ja iteraattorin toimintaa
    Hahmo hahmo = i.next(); 
    ids.append(" "+hahmo.getTunnusNro()); 
    }
    assertEquals("From: Hahmot line: 311", tulos, ids.toString()); 
    Iterator<Hahmo>  i=hahmot.iterator(); 
    assertEquals("From: Hahmot line: 314", true, i.next() == aku1); 
    assertEquals("From: Hahmot line: 315", true, i.next() == aku2); 
    assertEquals("From: Hahmot line: 316", true, i.next() == aku1); 
    try {
    i.next(); 
    fail("Hahmot: 318 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsi372 
   * @throws SailoException when error
   */
  @Test
  public void testEtsi372() throws SailoException {    // Hahmot: 372
    Hahmot hahmot = new Hahmot(); 
    Hahmo jasen1 = new Hahmo(); jasen1.parse("1|Ankka Aku|030201-115H|Paratiisitie 13|"); 
    Hahmo jasen2 = new Hahmo(); jasen2.parse("2|Ankka Tupu||030552-123B|"); 
    Hahmo jasen3 = new Hahmo(); jasen3.parse("3|Susi Sepe|121237-121V||131313|Perämetsä"); 
    Hahmo jasen4 = new Hahmo(); jasen4.parse("4|Ankka Iines|030245-115V|Ankkakuja 9"); 
    Hahmo jasen5 = new Hahmo(); jasen5.parse("5|Ankka Roope|091007-408U|Ankkakuja 12"); 
    hahmot.lisaa(jasen1); hahmot.lisaa(jasen2); hahmot.lisaa(jasen3); hahmot.lisaa(jasen4); hahmot.lisaa(jasen5); 
  } // Generated by ComTest END
}