package rpg.test;
// Generated by ComTest BEGIN
import java.io.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import rpg.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.03 22:42:32 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class HahmojenEsineetTest {



  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta117 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta117() throws SailoException {    // HahmojenEsineet: 117
    HahmojenEsineet harrasteet = new HahmojenEsineet(); 
    HahmonEsine miekka = new HahmonEsine(2,2); 
    HahmonEsine kirves = new HahmonEsine(2,2); 
    String tiedNimi = "testikelmit"; 
    File ftied = new File(tiedNimi+".dat"); 
    ftied.delete(); 
    try {
    harrasteet.lueTiedostosta(tiedNimi); 
    fail("HahmojenEsineet: 127 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    harrasteet.lisaa(kirves); 
    harrasteet.lisaa(miekka); 
    harrasteet.tallenna(); 
    harrasteet = new HahmojenEsineet(); 
    harrasteet.lueTiedostosta(tiedNimi); 
    Iterator<HahmonEsine> i = harrasteet.iterator(); 
    assertEquals("From: HahmojenEsineet line: 134", miekka.toString(), i.next().toString()); 
    assertEquals("From: HahmojenEsineet line: 135", true, i.hasNext()); 
    harrasteet.lisaa(miekka); 
    harrasteet.lisaa(kirves); 
    harrasteet.tallenna(); 
    assertEquals("From: HahmojenEsineet line: 139", true, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: HahmojenEsineet line: 141", true, fbak.delete()); 
  } // Generated by ComTest END
}