package rpg.test;
// Generated by ComTest BEGIN
import java.io.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import rpg.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.03 22:58:37 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class RpgTest {



  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta192 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta192() throws SailoException {    // Rpg: 192
    Rpg kerho = new Rpg(); 
    Hahmo aku1 = new Hahmo(); aku1.taytaAkuAnkka(); aku1.rekisteroi(); 
    Hahmo aku2 = new Hahmo(); aku2.taytaAkuAnkka(); aku2.rekisteroi(); 
    Esine esine1 = new Esine(); esine1.taytaMiekka(); esine1.rekisteroi(); 
    Esine esine2 = new Esine(); esine2.taytaMiekka(); esine2.rekisteroi(); 
    Rotu rotu1 = new Rotu(); rotu1.taytaRotu(1); 
    Rotu rotu2 = new Rotu(); rotu2.taytaRotu(2); 
    HahmonEsine he1 = new HahmonEsine(1,1); 
    HahmonEsine he2 = new HahmonEsine(2,2); 
    String hakemisto = "testikelmit"; 
    File dir = new File(hakemisto); 
    File ftied  = new File(hakemisto+"/nimet.dat"); 
    File ftied1  = new File(hakemisto+"/esineet.dat"); 
    File ftied2  = new File(hakemisto+"/hahmojen_esineet.dat"); 
    File ftied3  = new File(hakemisto+"/rodut.dat"); 
    dir.mkdir(); 
    ftied.delete(); 
    ftied1.delete(); 
    ftied2.delete(); 
    ftied3.delete(); 
    try {
    kerho.lueTiedostosta(hakemisto); 
    fail("Rpg: 222 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    kerho.lisaa(aku1); 
    kerho.lisaa(aku2); 
    kerho.lisaa(esine1); 
    kerho.lisaa(esine2); 
    kerho.lisaa(rotu1); 
    kerho.lisaa(rotu2); 
    kerho.lisaa(he1); 
    kerho.lisaa(he2); 
    kerho.talleta(); 
    Rpg rpg = new Rpg(); 
    rpg.lueTiedostosta(hakemisto); 
    Collection<Hahmo> kaikki = kerho.etsi("",-1); 
    Iterator<Hahmo> it = kaikki.iterator(); 
    assertEquals("From: Rpg line: 236", aku1, it.next()); 
    assertEquals("From: Rpg line: 237", aku2, it.next()); 
    assertEquals("From: Rpg line: 238", false, it.hasNext()); 
    kerho.lisaa(aku2); 
    kerho.lisaa(esine2); 
    kerho.lisaa(rotu2); 
    kerho.lisaa(he2); 
    kerho.talleta(); 
    assertEquals("From: Rpg line: 244", true, ftied.delete()); 
    assertEquals("From: Rpg line: 245", true, ftied1.delete()); 
    assertEquals("From: Rpg line: 246", true, ftied2.delete()); 
    assertEquals("From: Rpg line: 247", true, ftied3.delete()); 
    File fbak = new File(hakemisto+"/nimet.bak"); 
    File fbak1 = new File(hakemisto+"/esineet.bak"); 
    File fbak2 = new File(hakemisto+"/hahmojen_esineet.bak"); 
    File fbak3 = new File(hakemisto+"/rodut.bak"); 
    assertEquals("From: Rpg line: 252", true, fbak.delete()); 
    assertEquals("From: Rpg line: 253", true, fbak1.delete()); 
    assertEquals("From: Rpg line: 254", true, fbak2.delete()); 
    assertEquals("From: Rpg line: 255", true, fbak3.delete()); 
    assertEquals("From: Rpg line: 256", true, dir.delete()); 
  } // Generated by ComTest END
}